# php7 nginx mysql5.7で作る開発環境
version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs/nginx:/var/log/nginx
      - ./data/html:/var/www/html
  php:
    build: ./php7
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_HOST: db
    volumes:
      - ./data/html:/var/www/html
      - ./php7/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/logs/mysql:/var/log/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql

